version: '3.8'

services:
  kong-database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong_password
    volumes:
      - kong-database:/var/lib/postgresql/data

  kong:
    image: kong:latest
    restart: always
    depends_on:
      - kong-database
    entrypoint: ["/wait-for-it.sh", "kong-database:5432", "--"]
    command: ["kong", "reload"]
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"  # Proxy port
      - "8001:8001"  # Admin port
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge

volumes:
  kong-database:
