// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"UserService/config"
	"UserService/internal/handlers"
	"UserService/internal/repository"
	"UserService/internal/services"
)

// Injectors from wire.go:

// Wire khởi tạo tất cả các phụ thuộc và trả về UserHandler
func InitializeUserHandler() *handlers.UserHandler {
	db := config.InitDB()
	userRepository := repository.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userHandler := handlers.NewUserHandler(userService)
	return userHandler
}
