version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql           # Đặt DB_HOST thành tên dịch vụ MySQL
      DB_USER: root          # Tên người dùng
      DB_PASSWORD: 123456   # Mật khẩu
      DB_NAME: user      # Tên cơ sở dữ liệu
      DB_PORT: 3306            # Cổng MySQL
      DB_TYPE: mysql
    ports:
      - "3000:3000"            # Mở cổng 8080 cho ứng dụng
    depends_on:
      - mysql
    networks:
      - kong-net

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # Mật khẩu cho root
      MYSQL_DATABASE: user        # Tên cơ sở dữ liệu
    ports:
      - "3306:3306"                     # Mở cổng 3306 cho MySQL
    networks:
      - kong-net  
networks:
  kong-net:
    driver: bridge      